<h3>1. Knihovny a moduly pro matematické výpočty</h3>

Zadání:
V tomto kurzu jste se učili s některými vybranými knihovnami. Některé sloužily pro rychlé vektorové operace, jako numpy, některé mají naprogramovány symbolické manipulace, které lze převést na numerické reprezentace (sympy), některé mají v sobě funkce pro numerickou integraci (scipy). Některé slouží i pro rychlé základní operace s čísly (numba).

Vaším úkolem je změřit potřebný čas pro vyřešení nějakého problému (např.: provést skalární součin, vypočítat určitý integrál) pomocí standardního pythonu a pomocí specializované knihovny. Toto měření proveďte alespoň pro 5 různých úloh (ne pouze jiná čísla, ale úplně jiné téma) a minimálně porovnejte rychlost jednoho modulu se standardním pythonem. Ideálně proveďte porovnání ještě s dalším modulem a snažte se, ať je kód ve standardním pythonu napsán efektivně. ​


In [ ]:
import math
import time
import numpy as np
import scipy.integrate as spi
import random

1. **Faktoriál**

In [ ]:
# za použítí Pythonu
cas_start = time.time() # začátek spuštění odečteme od konce

faktorial = 5 # číslo pro které faktoriál hledáme
vysledek = 1

for i in range(1, faktorial + 1):
    vysledek *= i

cas_konec = time.time()

print(f"výsledek:{vysledek}")
print(f"za použití pythonu {cas_konec - cas_start}")

# za použití knihovny

cas_start = time.time()
faktorial = math.factorial(5)
cas_konec = time.time()

print(f"výsledek: {faktorial}")
print(f"za použití knihovny: {cas_konec - cas_start}")

výsledek:120
za použití pythonu 0.00031065940856933594
výsledek: 120
za použití knihovny: 0.00011587142944335938


2. **Skalární součin**

In [ ]:
# za použití pythonu
cas_start = time.time()

a = [1,2,3]
b = [4,5,6]

vysledek = sum(i*j for i, j in zip(a,b))

cas_konec = time.time()

print(f"vysledek: {vysledek}")
print(f"za použití pythonu {cas_konec - cas_start}")

# za použití knihovny
cas_start = time.time()
a = [1,2,3]
b = [4,5,6]

vysledek = np.dot(a,b)
cas_konec = time.time()

print(f"výsledek: {vysledek}")
print(f"za použití knihovny: {cas_konec - cas_start}")

vysledek: 32
za použití pythonu 0.00031876564025878906
výsledek: 32
za použití knihovny: 0.0002677440643310547


3. **Určitý integrál**

In [ ]:
# za použití pythonu
cas_start = time.time()

def f(x):
    return x**2

a, b = 0, 1 # interval
dx = 0.001

x = [i*dx for i in range(int(a/dx), int(b/dx))] # seznam hodnot x

vysledek = sum([f(i)*dx for i in x]) # aproximace určitého integrálu
cas_konec = time.time()

print(f"výsledek: {vysledek}")
print(f"za použití pythonu {cas_konec - cas_start}")

# za použití knihovny
cas_start = time.time()
a, b = 0, 1
vysledek, odhad_chyb = spi.quad(f, a, b)
cas_konec = time.time()

print(f"výsledek: {vysledek}")
print(f"za použití knihovny: {cas_konec - cas_start}")

vysledek: 0.33283350000000034
za použití pythonu 0.0010683536529541016
výsledek: 0.33333333333333337
za použití knihovny: 0.00024247169494628906


4. **Násobení matic**

In [ ]:
# za použití pythonu
cas_start = time.time()

a = [[1,2,3],[4,5,6],[7,8,9]]
b = [[10,11,12],[13,14,15],[16,17,18]]

vysledek = [[sum(x*y for x,y in zip(row, col)) for col in zip(*b)] for row in a]
cas_konec = time.time()

print(f"výsledek:")
for i in vysledek:
    print(i)

print(f"za použití pythonu {cas_konec - cas_start}")

# za použití knihovny
cas_start = time.time()

a = [[1,2,3],[4,5,6],[7,8,9]]
b = [[10,11,12],[13,14,15],[16,17,18]]

vysledek = np.dot(a, b)
cas_konec = time.time()

print("výsledek:")
print(vysledek)
print(f"za použití knihovny: {cas_konec - cas_start}")

výsledek:
[84, 90, 96]
[201, 216, 231]
[318, 342, 366]
za použití pythonu 0.00039005279541015625
výsledek:
[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
za použití knihovny: 0.0003306865692138672


5. **Generování náhodných čísel**

In [ ]:
# za použítí Pythonu
cas_start = time.time() # začátek spuštění odečteme od konce

nahodne_cislo = [random.random() for i in range(0,10)]
cas_konec = time.time()

print(f"výsledné číslo:{nahodne_cislo}")
print(f"za použití pythonu {cas_konec - cas_start}")

# za použití knihovny

cas_start = time.time()

nahodne_cislo_np = np.random.rand(10)
cas_konec = time.time()

print(f"výsledek: {nahodne_cislo_np}")
print(f"za použití knihovny: {cas_konec - cas_start}")

výsledné číslo:[0.29987220861612496, 0.29604786164941155, 0.672805205634003, 0.0025643962172680057, 0.5747420197839518, 0.5717784058653891, 0.8873326186069473, 0.7280504299175735, 0.07883521726561982, 0.3039232503663103]
za použití pythonu 0.00016999244689941406
výsledek: [0.38592673 0.46446    0.39699489 0.05786543 0.30617328 0.75286801
 0.72587172 0.2543539  0.04775212 0.67468206]
za použití knihovny: 0.0001685619354248047
